### ISSUE TITLE
Create a .NET Core library (for OneTrueError.Client base package)

### ISSUE THREAD

**Issue by gauffininteractive** [onetrueerror/onetrueerror.client#6]
Need to remove unsupported features like WMI for the Core library

**Comment by pichardoSoftware** [comment]
So you want a full migration to ASP core?

**Comment by gauffininteractive** [comment]
yes. I'll create another issue for the ASP.NET Core package

**Comment by onetrueerror** [comment]
Done: https://github.com/onetrueerror/OneTrueError.Client.NetStandard
